version: "3.7"
services:
    romiq1:
        container_name: romiq1
        build:
            context: .
            dockerfile: ./services/romiq/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
        volumes:
            - ./services/romiq:/home/bdb/app
            - ./common_drive/reports:/mnt/common_drive/reports
        expose:
            - 5000
        env_file:
            - ./.env.dev
    romiq2:
        container_name: romiq2
        build:
            context: .
            dockerfile: ./services/romiq/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
        volumes:
            - ./services/romiq:/home/bdb/app
            - ./common_drive/reports:/mnt/common_drive/reports
        expose:
            - 5000
        env_file:
            - ./.env.dev
    shinyapp:
        container_name: shinyapp
        build:
            context: .
            dockerfile: ./services/shinyapp/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
        restart: unless-stopped
        expose:
            - 3838
        volumes:
            - ./common_drive:/mnt/common_drive
    nginx:
        container_name: nginx
        build: ./services/nginx
        links:
            - romiq1
            - romiq2
        ports:
            - 1888:80
        restart: unless-stopped
