version: "3.7"
services:
    romiq1:
        container_name: romiq1
        # image: bdbcontainerreg.azurecr.io/bdb-ctnr-romiq:cf1d
        image: bdbcontainerreg.azurecr.io/bdb-romiq-nopgdb:latest
        volumes:
            - ./common_drive/reports:/mnt/common_drive/reports
        env_file:
            - ./.env.dev
    romiq2:
        container_name: romiq2
        image: bdbcontainerreg.azurecr.io/bdb-romiq-nopgdb:latest
        volumes:
            - ./common_drive/reports:/mnt/common_drive/reports
        env_file:
            - ./.env.dev
    pyapi1:
        container_name: pyapi1
        build:
            context: .
            dockerfile: ./services/pyapi/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
                HOSTNAME: romiq1
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        volumes:
            - ./services/pyapi:/home/bdb/pyapi
        expose:
            - 5000
        env_file:
            - ./.env.dev
    pyapi2:
        container_name: pyapi2
        build:
            context: .
            dockerfile: ./services/pyapi/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
                HOSTNAME: romiq2
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        volumes:
            - ./services/pyapi:/home/bdb/pyapi
        expose:
            - 5000
        env_file:
            - ./.env.dev
    shinyapp:
        container_name: shinyapp
        build:
            context: .
            dockerfile: ./services/shinyapp/Dockerfile
            args:
                PASSWORD: pass
                UNAME: bdb
                HOSTNAME: pyapi2
        restart: unless-stopped
        expose:
            - 3838
        volumes:
            - ./common_drive:/mnt/common_drive
    nginx:
        container_name: nginx
        build: ./services/nginx
        links:
            - pyapi1
            - pyapi2
        ports:
            - 1888:80
            - 1889:81
        restart: unless-stopped
volumes:
    pg-data:
